name: flamingo_9B_v1
hf_root: OpenFlamingo-9B-deprecated
flamingo_checkpoint_dir: ${oc.env:CHECKPOINT_PATH}/${infer_model.hf_root}/
lang_encoder_path: ${oc.env:INFER_MODEL_CPK_DIR}/llama-7b
tokenizer_path: ${infer_model.lang_encoder_path}
cross_attn_every_n_layers: 4
load_from_local: true

caption_prompt_template: "Output:<X>"
vqa_prompt_template: "Question:<Q> Short answer:<A>"

caption_instruction: ""
vqa_instruction: ""

icd_join_char: "<|endofchunk|>"

caption_split_token: "Output:"
vqa_split_token: "Short answer:"

init_device: "cpu"