name: idefics_9B
hf_root: "${oc.env:INFER_MODEL_CPK_DIR}/idefics-9b"
load_from_local: true

caption_prompt_template: "Caption:<X>"
vqa_prompt_template: "Question:<Q> Short answer:<A>"
ocr_vqa_prompt_template: "Question:<Q> Answer:<A>"

ocr_vqa_instruction: "Answer the question based on the image.\n\n"
caption_instruction: ""
vqa_instruction: "Instruction: provide an answer to the question. Use the image to answer.\n"


icd_join_char: "\n"
caption_split_token: "Caption:"
vqa_split_token: "Short answer:"
ocr_vqa_split_token: "Answer:"