name: idefics2-8b-base
model_name_or_path: "${oc.env:INFER_MODEL_CPK_DIR}/idefics2-8b-base"

caption_prompt_template: "Caption:<X>"
vqa_prompt_template: "Question:<Q> Short answer:<A>"

caption_instruction: ""
vqa_instruction: "Instruction: provide an answer to the question. Use the image to answer.\n"


icd_join_char: "\n"
caption_split_token: "Caption:"
vqa_split_token: "Short answer:"
