name: Qwen1.5-1.8B

model_name: ${oc.env:INFER_MODEL_CPK_DIR}/Qwen1.5-1.8B
load_from_local: true

sst2_prompt_template: 
    0: "</text> It's negative movie review."
    1: "</text> It's positive movie review."

icd_join_char: "\n"

sst2_split_token: "It's"

init_device: "cuda"

query_text_feature_field: "text"