_target_: lever_lm.candidate_sampler.mix_sampler.MixSimSampler

sampler_name: MixSampler
candidate_num: ${cand_num}
cache_dir: "${result_dir}/cache"
overwrite: false
dataset_name: ${dataset.name}
clip_model_name: "openai/clip-vit-large-patch14"

feature_cache_filename: "${task.task_name}-${dataset.name}-${sampler.clip_model_name}"
text_field_name: "${task.sim_text_field}"
img_field_name: "${task.sim_image_field}"
device: ${device}
candidate_set_encode_bs: 128
sampler_ratio: 
  RandSampler: 0.5
  TextSimSampler: 0.25
  ImgSimSampler: 0.25

anchor_sample_num: ${sample_num}
index_ds_len: ${dataset.train_ds_len}
