_target_: lever_lm.candidate_sampler.text_sim_sampler.TextSimSampler

sampler_name: TextSimSampler
candidate_num: ${cand_num}
cache_dir: "${result_dir}/cache"
overwrite: false
dataset_name: ${dataset.name}
clip_model_name: "openai/clip-vit-large-patch14"

feature_cache_filename: "${task.task_name}-${dataset.name}-${sampler.clip_model_name}-TextFeatures.pth"
text_field_name: "${task.sim_text_field}"
device: ${device}
candidate_set_encode_bs: 128

anchor_sample_num: ${sample_num}
index_ds_len: ${dataset.train_ds_len}
