_target_: icd_lm.dataset_module.icd_lm_ds.ICDLMDataset


index_set_length: ${dataset.train_ds_len}

query_image_field: null
query_text_field: ${task.query_text_feature_field}
icd_image_field: null
icd_text_field: ${task.icd_text_feature_field}

threshold: 0.0
reverse_seq: false