_target_: lever_lm.dataset_module.lever_lm_ds.LeverLMDataset


index_set_length: ${dataset.train_ds_len}

query_image_field: ${task.image_field}
query_text_field: null
icd_image_field: ${task.image_field}
icd_text_field: ${task.icd_text_feature_field}


threshold: 0.0
reverse_seq: false