task_name: vqa
# use for get prompt for flamingo
# for get prompt of openicl
template: "${infer_model.vqa_prompt_template}"

column_token_map:
  question: "<Q>"
  answer: "<A>"

input_columns: ["question", "answer"]
output_column: "answer"
instruction: ${infer_model.vqa_instruction}

image_field: "image"

# use for train model and inference icd feature field
icd_text_feature_field: "question"
query_text_feature_field: "question"

# sim fields:
sim_text_field: "question"
sim_image_field: "image"

# for flamingo inference
gen_args:
  max_new_tokens: 5
  num_beams: 3
  length_penalty: 0.0
  min_new_tokens: 0

other_save_field: ['question', 'answer', 'image_id', 'answers', 'question_id']


split_token: "${infer_model.vqa_split_token}"