# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - flamingo: flamingo_9B
  - dataset: coco2017
  - task: caption


# get candidate_set args
candidate_set_num: 64
candidate_set_method: "random"

# recall args
sim_model_type: "openai/clip-vit-large-patch14"
candidate_set_encode_bs: 64

# generation args:
beam_size: 5
few_shot_num: 2
batch_size: 32
device: "cuda"
precision: bf16
sample_num: 5000

# Others
result_dir: "${oc.env:RESULT_DIR}"
gpu_ids: [0]
# load several models at the same time will cost large memory.
# use sleep to load one by one.
sleep_time: 90


# hydra
hydra:
  run:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${task.task_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${result_dir}/hydra_output/multirun/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}