# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - train: query_img_icd_img_text
  - dataset: coco2017
  - task: caption


# data args
data_files: ???
train_ratio: 0.9
batch_size: 64
num_workers: 16


# Trainer
trainer_args:
  devices: 1
  strategy: ddp
  accelerator: gpu
  precision: "16-mixed"
  log_every_n_steps: 10
  val_check_interval: 0.5
  max_epochs: 20
  fast_dev_run: false


# train args:

lr: 1e-4
weight_decay: 1e-3
warm_steps: 0.05



# Others
ex_name: "debug"
result_dir: "${oc.env:RESULT_DIR}"
seed: 42
dirpath: "${oc.env:RESULT_DIR}/model_cpk/${task.task_name}/${ex_name}"




# wandb_args
wandb_args:
  save_dir: "${oc.env:RESULT_DIR}/wandb_logs"
  name: "${ex_name}"
  project: "LeverLM"
  log_model: false

  

hydra:
  run:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${ex_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${ex_name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
